### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by w3hidayath** [vilenarios/Arweave-Monitor#3]
How can i resolve this issue. Please help
python3.8 ./arweave-monitor.py
Traceback (most recent call last):
  File "./arweave-monitor.py", line 55, in <module>
    oldest_date = oldest_log_file[1].split("-")
IndexError: list index out of range

**Comment by RecycledMiner** [comment]
Did you manage to get this resolved - I have a very similar error?
Traceback (most recent call last):
  File "arweave-monitor.py", line 51, in <module>
    latest_log_file = max(all_log_files, key=os.path.getctime)
ValueError: max() arg is an empty sequence
